/A/@XSeite wird aufgebaut               ˜SH291/O& &16@@alxGGO`yDmI[@y|JxAYYYKYHGA& " 5@&0XQ_]/DAA›2@# REA‡
Die tÈaglichenŒ u
AbgasproblemeŒ u
habenŒ ~ F
die meistenŒ y
verdrÈangt.Œ ~ ~ u›0@
Wir nicht.Œ i›2@€ZEIT ZUM UMDENKEN ›1@‚Ðg VBUSSE & BAHNEN   # GA#!0@GOxO@_G^L^N.0-!,!-@^FGGC.0-!,!-@OCGCcCG@O0x@@`G`Gpcp.0^N"^L_GO@OxG@ 0GC!FG@^-,!-! 0CCCaCC@G-,!-! 0cp#GpG``@|@ #,0!GE`DXDVDaE@G 0!xAhFHZHaH@hx 0!O|^^_~^N^^XFO| 