all: decode_cept cut_btx cut_btx_pc_online

decode_cept:
	cc -o decode_cept decode_cept.c

cut_btx:
	cc -o cut_btx cut_btx.c

cut_btx_pc_online:
	cc -o cut_btx_pc_online cut_btx_pc_online.c

clean:
	rm -f decode_cept cut_btx cut_btx_pc_online