use super::editor::*;
use super::pages::*;

pub fn create(pageid: &str) -> Option<Page> {
    let meta = Meta {
        clear_screen: Some(false),
        links: None,
        publisher_color: Some(7),
        inputs: Some(Inputs {
            fields: vec!(
                InputField {
                    name: "user_id".to_owned(),
                    hint: Some("Teilnehmernummer oder # eingeben".to_owned()),
                    line: 18,
                    column: 26,
                    height: 1,
                    width: 10,
                    bgcolor: Some(12),
                    fgcolor: Some(3),

                    typ: InputType::Normal,
                    cursor_home: false,
                    clear_line: false,
                    legal_values: None,
                    end_on_illegal_character: false,
                    end_on_legal_string: false,
                    echo_ter: false,
                    command_mode: false,
                    no_navigation: false,
                    default: None,
                    validate: None,
                },
                InputField {
                    name: "ext".to_owned(),
                    hint: Some("Mitbenutzer oder # eingeben".to_owned()),
                    line: 18,
                    column: 37,
                    height: 1,
                    width: 1,
                    bgcolor: Some(12),
                    fgcolor: Some(3),
                    typ: InputType::Number,
                    cursor_home: true,
                    default: Some("1".to_owned()),

                    clear_line: false,
                    legal_values: None,
                    end_on_illegal_character: false,
                    end_on_legal_string: false,
                    echo_ter: false,
                    command_mode: false,
                    no_navigation: false,
                    validate: None,
                },
                InputField {
                    name: "password".to_owned(),
                    hint: Some("Nächstes Feld mit #; Leer für Gast".to_owned()),
                    line: 20,
                    column: 26,
                    height: 1,
                    width: 14,
                    bgcolor: Some(12),
                    fgcolor: Some(3),
                    typ: InputType::Password,
                    validate: Some("call:Login_UI.callback_login".to_owned()),

                    cursor_home: false,
                    clear_line: false,
                    legal_values: None,
                    end_on_illegal_character: false,
                    end_on_legal_string: false,
                    echo_ter: false,
                    command_mode: false,
                    no_navigation: false,
                    default: None,
                }
            ),
            confirm: false,
            no_55: false,
            // target: "page:000001a".to_owned(),
            // no_navigation: true
        }),
        publisher_name: None,
        cls2: None,
        parallel_mode: None,
        palette: None,
        include: None,
        autoplay: None,
    };

    let mut page = Page::new(meta);
    page.cept.from_aa(
        &[
            "    ████████████████████████████████████████████████   ",
            "   █                                                █  ",
            "  █                                                  █ ",
            " █                                                    █",
            " █                                                    █",
            " █                                                    █",
            " █                ████████████████████                █",
            " █             ██████████████████████████             █",
            " █           ██████████████████████████████           █",
            " █          ████████████████████████████████          █",
            " █         ███████████            ███████████         █",
            " █         ██████████              ██████████         █",
            " █         ██████████     ████     ██████████         █",
            " █         █████████    ████████    █████████         █",
            " █          ██████     ██████████     ██████          █",
            " █           ███   ███ ██████████ ███   ███           █",
            " █               █████ ██████████ █████               █",
            " █             ███████ ██████████ ███████             █",
            " █            ████████ ██████████ ████████            █",
            " █            ████████ ██████████ ████████            █",
            " █            ████████ ██████████ ████████            █",
            " █            █████████ ████████ █████████            █",
            " █            ██████████  ████  ██████████            █",
            " █            ████████████    ████████████            █",
            " █            ████████████████████████████            █",
            " █            ████████████████████████████            █",
            " █            ████████████████████████████            █",
            " █                                                    █",
            " █                                                    █",
            " █                                                    █",
            " █   ███ █ █   █        █   █                         █",
            " █   █ █   █   █        █              █          █   █",
            " █   █ █ █ █ ███ ███ ██ ███ █ ██ █████ ██ ███ █ █ ██  █",
            " █   ██  █ █ █ █ █   █  █ █ █ █  █ █ █ █  █ █ █ █ █   █",
            " █   █ █ █ █ █ █ ███ █  █ █ █ █  █ █ █ █  ███  █  █   █",
            " █   █ █ █ █ █ █   █ █  █ █ █ █  █ █ █ █  █   █ █ █   █",
            " █   ███ █ █ ███ ███ ██ █ █ █ █  █ █ █ ██ ███ █ █ ██  █",
            " █                                                    █",
            " █                                                    █",
            " █                                                    █",
            "  █                                                  █ ",
            "   █                                                █  ",
            "    ████████████████████████████████████████████████   "
        ], 6);

        Some(page)
}